name: soultypes_app

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  cloud_functions: ^5.3.4
  google_sign_in: ^6.1.6
  riverpod: ^2.3.0
  flutter_riverpod: ^2.3.0
  go_router: ^7.0.0
  freezed_annotation: ^2.3.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  freezed: ^2.3.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
